
version: "3.8"
services:

  web:
    image: "mariobd7/gbm_code_challenge"
    environment:
      - TZ=America/Mexico_City
      - REDIS_HOST=redis
    ports:
      - "80:80"
    links:
      - redis

  redis:
    image: "redis"
    ports:
      - "6379:6379"